spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.20.10.7/sell?characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.20.10.7
    port: 6379

server:
    context-path: /sell

path:
  realPath: http://hytc.natapp1.cc
  projectHeader: /sell

wechat:
    myAppId: wx367760769f18a4e1
    myAppSecret: 72086a7c0d0a12e8977e14eb184b6676
    mchId:
    mchKey:
    keyPath:
    notifyUrl: http://hytc.natapp1.cc/sell/pay/notify

logging:
  level: payease.dataobject.mapper:trace
